import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatCurrency, formatDate } from './formatters';

export const generateMonthlyReport = (monthLabel, orders, commissionRate, agencyDetails) => {
  const doc = new jsPDF();
  const totalRevenue = orders.reduce((sum, o) => sum + o.totalAmount, 0);
  const totalCommission = totalRevenue * commissionRate;

  // Header
  doc.setFontSize(22);
  doc.setTextColor(99, 102, 241); // Indigo
  doc.text('COMMISSION INVOICE', 14, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Billing Period: ${monthLabel}`, 14, 32);
  doc.text(`Generated: ${formatDate(new Date())}`, 14, 37);

  // Agency Details
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.text('FROM:', 14, 50);
  doc.setFontSize(10);
  doc.text(agencyDetails.name || 'Your Agency Name', 14, 55);
  doc.text(agencyDetails.email || 'billing@agency.com', 14, 60);

  // Client Details
  doc.setFontSize(12);
  doc.text('BILL TO:', 120, 50);
  doc.setFontSize(10);
  doc.text('Duo Designs', 120, 55);
  doc.text('Bangalore, India', 120, 60);

  // Summary Table
  doc.autoTable({
    startY: 75,
    head: [['Description', 'Base Amount', 'Rate', 'Total Commission']],
    body: [
      [
        `Agency Service Fee - ${monthLabel}`,
        formatCurrency(totalRevenue),
        `${(commissionRate * 100).toFixed(1)}%`,
        formatCurrency(totalCommission)
      ]
    ],
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241] }
  });

  // Orders Summary Title
  doc.setFontSize(12);
  doc.text('DETAILED ORDER BREAKDOWN', 14, doc.lastAutoTable.finalY + 15);

  // Detailed Orders Table
  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 20,
    head: [['Order ID', 'Date', 'Amount', '5% Fee']],
    body: orders.map(o => [
      `#${o.orderId}`,
      formatDate(o.createdAt, 'dd MMM'),
      formatCurrency(o.totalAmount),
      formatCurrency(o.totalAmount * commissionRate)
    ]),
    foot: [['TOTAL', '', formatCurrency(totalRevenue), formatCurrency(totalCommission)]],
    theme: 'striped',
    headStyles: { fillColor: [51, 65, 85] }
  });

  // Bank Details
  const finalY = doc.lastAutoTable.finalY + 20;
  doc.setFontSize(12);
  doc.text('PAYMENT INFORMATION:', 14, finalY);
  doc.setFontSize(10);
  doc.text(`Bank: ${agencyDetails.bankName || 'N/A'}`, 14, finalY + 7);
  doc.text(`Account Number: ${agencyDetails.accountNo || 'N/A'}`, 14, finalY + 12);
  doc.text(`IFSC: ${agencyDetails.ifsc || 'N/A'}`, 14, finalY + 17);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Thank you for your partnership. Generated by Agency Revenue Tracker.', 14, 285);

  doc.save(`DuoDesigns_Commission_${monthLabel.replace(' ', '_')}.pdf`);
};
